name: Sandbox - Build and Deploy
on:
  push:
    branches: main
    paths-ignore: 
      - '**.yml'
  workflow_dispatch:
    
jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
#first, we need to checkout our mule application's code
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and deploy artifact to sandbox
#run the maven deploy lifecycle. The -B indicated a batch process,
#which reduces the amount of logging the deployment does
        run: mvn -B deploy -DmuleDeploy -s .maven/settings.xml
      - name: Set Job Success
        if: ${{ success() }}
        run: |
          echo "JOB_STATE=success" >> $GITHUB_ENV
      - name: Set Job Fail
        run: |
          echo "JOB_STATE=fail" >> $GITHUB_ENV
      - name: Send Job Run Result
        id: api-request
        if: ${{ always() }}
        uses: muhfaris/request-action@v0.1.2
        with:
          url: "https://cicd-status-processor-knpvkn.5sc6y6-4.usa-e2.cloudhub.io/status?state=${{ env.JOB_STATE }}&run_id=${{ github.run_id }}&repo_owner=${{ env.GITHUB_REPOSITORY_OWNER }}&repo_name=${{ env.GITHUB_REPOSITORY }}"
          method: GET
      - name: Show API Response Status
        if: always()
        run: |
          echo "Response Status: ${{ steps.api-request.outputs.response-status }}"

      - name: Show API Response Data
        if: always()
        run: |
          echo "Response Data: ${{ steps.api-request.outputs.response-data }}"
#Pass in the secrets we need for deployment as environment variables
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          PLATFORM_USERNAME: ${{ secrets.PLATFORM_USERNAME }}
          PLATFORM_PASSWORD: ${{ secrets.PLATFORM_PASSWORD }}
          SANDBOX_CLIENT_ID: ${{ secrets.SANDBOX_CLIENT_ID }}
          SANDBOX_CLIENT_SECRET: ${{ secrets.SANDBOX_CLIENT_SECRET }}
          BUS_GROUP_ID: ${{ secrets.BUS_GROUP_ID }}
  
